name: todolist
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  
  cloud_firestore: ^4.4.3
  flutter_bloc: ^8.1.2
  flutter_animate: ^4.1.0
  cool_alert: ^1.1.0
  load_switch: ^1.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.3.2
  bloc_test: ^9.1.1
  build_runner: ^2.2.1
  
flutter:

  uses-material-design: true
